# Generated by Django 5.1.2 on 2024-10-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='Gmail',
        ),
    ]
