# Generated by Django 5.0.4 on 2024-10-30 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0005_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 5, 40, 51, 831978, tzinfo=datetime.timezone.utc)),
        ),
    ]
