# Generated by Django 5.0.4 on 2024-10-30 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0008_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premiumMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 9, 44, 13, 636870, tzinfo=datetime.timezone.utc)),
        ),
    ]
