# Generated by Django 5.0.4 on 2024-10-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0009_profile_is_premiummember_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 18, 51, 0, 129206, tzinfo=datetime.timezone.utc)),
        ),
    ]
