# Generated by Django 5.0.4 on 2024-11-04 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0010_alter_episode_image_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 15, 30, 46, 445976, tzinfo=datetime.timezone.utc)),
        ),
    ]
