# Generated by Django 5.0.4 on 2024-11-04 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0011_alter_subscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0.5)),
                ('current_audio_index', models.PositiveIntegerField(blank=True, null=True)),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 15, 31, 18, 744843, tzinfo=datetime.timezone.utc)),
        ),
    ]
