# Generated by Django 5.1.2 on 2024-12-02 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC', '0013_episode_is_premium_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_premiumMember',
            new_name='is_premium',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 21, 38, 31, 292073, tzinfo=datetime.timezone.utc)),
        ),
    ]
